### ISSUE TITLE
Status transition  

### ISSUE THREAD

**Issue by tumekee** [apexad/homebridge-garagedoor-command#12]
Hi , 

Great Plugin ! a million times better than the http end point alternatives 

Just Noticed the states from open to closing and closed to opening, if the current state is OPEN and the next status is CLOSING , the home app shows opening  ( when it should be closing ). I tried to inverted the status on the status script ,( at the end of the day the only thing you see is on the home app ) , which made no difference. it appears if closing or opening follows either the open or the closed state , open will go to opening and closed will go to closing.  

any help would be apricated !

![img_2999](https://user-images.githubusercontent.com/20364311/48974421-bb7fcc00-f0bd-11e8-97f4-63a389969475.JPG)

**Comment by apexad** [comment]
I am not able to duplicate this, so confirm that your state scripts are reporting the correct status, espefially if you are using the recently added polling option.

Just as a test, try turning polling off to see if that fixes the issue.

**Comment by tumekee** [comment]
sorry for the late reply lol, I went overseas and just put up with the issue for a year , I tried to disable  polling and no luck , its very odd indeed.
