### ISSUE TITLE
D1 Mini Sample File

### ISSUE THREAD

**Issue by MeneerOom** [apexad/homebridge-garagedoor-command#14]
Hi there

After a long search, this is exactly what I'm looking for. I would just like to please ask if you could perhaps share sample code for an Arduino + D1 Mini, Relay Shield and Magnetic Reed Switch - I'm having trouble sending a response to Homebridge and I'm not finding a lot of resources on it.

Much appreciated

**Comment by apexad** [comment]
So this plugin is meant to simply run a command to open/close/check status of a garage door.  The command is run by the plugin on the same server that is running homebridge.

What is that your normally run to do this with your setup? or what needs to be done on the iPhone?

**Comment by MeneerOom** [comment]
I've worked a little more and once I make something worth sharing, I'll definitely make a pull request with some sample code.

I would just like to check the following with you: This is my folder structure:
```.homebridge
|
└-garage
  |
  └-open.py
  └-open.sh
  └-close.py
  └-close.sh
  └-state.py
  └-state.sh```

When I run $homebridge I'm getting the following error:
![Screenshot 2019-03-26 at 18 12 10](https://user-images.githubusercontent.com/15004267/55014000-e7bb4300-4ff2-11e9-8c5e-53f9aee390cb.png)

Does this look like a familiar issue you can help with?

**Comment by apexad** [comment]
My guess is either a permissions issue with that folder or a context issue. Best to use the full path:

/home/pi/garage/open.sh
Or whatever

**Comment by apexad** [comment]
I assume this is resolved.  Please re-open if it is not.
