### ISSUE TITLE
Installing Garage Door Command on iPad

### ISSUE THREAD

**Issue by tmoore79** [apexad/homebridge-garagedoor-command#15]
Hello, my friend and I have been trying to get your App to work on his Ipad.
We've got Homebridge running on the Raspberry Pi and installed 
your 'Garage-Door-Command' App.

I've edited the open.sh & close.sh to say:
echo OPENING  followed by ./scripts/open.py
and
echo CLOSING followed by ./scripts/close.py

The python scripts don't do anything yet!

We've restarted homebridge and it's saying:
"[Front Garage Door] Error: Command Failed ./scripts/state.sh not found."

We have also removed the command to look for state in the config.json file,
but don't know why it's not finding it!

Any assitance would be helpful.
Many Thanks

Morebits and his Friend.

open.sh:
```
echo OPENING
python ~/.homebridge/scripts/open.py

```
close.sh:
```
echo CLOSING
python ~/.homebridge/scripts/close.py

```

**Comment by lunettepaysano** [comment]
Make sure you provide the full path of your commands in your config.json file. You should probably do the same in sh files too.

**Comment by apexad** [comment]
Yes, no relative paths. Use the full path.

**Comment by Jborn4christ** [comment]
Feel like I am getting close, but still getting error. Any ideas? On Windows 10.
[6/19/2019, 4:41:46 PM] [Garage Door] Error: Command failed: node C:/Users/Chambers/.homebridge/scripts/node-aladdin-connect-garage-door//state.js
internal/modules/cjs/loader.js:626

**Comment by apexad** [comment]
Perhaps extra / see you have a // there after garage-door

**Comment by Jborn4christ** [comment]
I fixed that but am now getting new error related to token. I left a new issue regarding that on the plugin.
