### ISSUE TITLE
Plugin Polls Door State Twice

### ISSUE THREAD

**Issue by tastycorn** [apexad/homebridge-garagedoor-command#18]
When I open the Home app on my phone, the plugin checks the state of my doors twice for some reason. It appears as if the check_state script is being run twice simultaneously by looking at the time stamps. Since the check_state script pulls an output GPIO pin high then listens on another pin to see if the reed switch on the door is open or closed, running it twice screws something up and reports different states for each instance of the script as shown in the attached screenshot:
<img width="682" alt="Screen Shot 2019-09-13 at 2 59 47 PM" src="https://user-images.githubusercontent.com/23389178/64894754-d107b780-d637-11e9-89e9-9d424a973287.png">
After this initial screwup, if you ask Siri about the state of each door, it will report correctly until the next time you open the Home app, when it will run the scripts twice again. How do I stop this behaviour?

The configuration of one of my doors in config.json is:

            "accessory": "GarageCommand",
            "name": "Left Door",
            "open": "/home/pi/.homebridge/scripts/openleft.sh",
            "close": "/home/pi/.homebridge/scripts/closeleft.sh",
            "state": "/home/pi/.homebridge/scripts/stateleft.sh",
            "status_update_delay": 18
 
stateleft.sh contains:

            python ~/.homebridge/scripts/stateleft.py
            if [ $? -eq 1 ]
            then
             	echo "OPEN"
            else
            	echo "CLOSED"
            fi

And stateleft.py contains:

            import RPi.GPIO as GPIO
            import sys
            import time
            
            GPIO.setmode(GPIO.BCM)
            GPIO.setup(27, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)
            GPIO.setup(22, GPIO.OUT, initial=GPIO.HIGH)
            time.sleep(.5)
            exitcode = GPIO.input(27)
            GPIO.cleanup()
            time.sleep(.5)
            if exitcode == 1:
            	sys.exit(1)
            else:
            	sys.exit(0)

**Comment by HunterDG** [comment]
Same here, never had time to investigate a fix, Though I don't think the door state results in confusion, just that it polls twice.  I use calls to a 3rd party online garage door control service that uses the opener's own method of determining state, so perhaps that's why I don't get the confusion.  

<img width="630" alt="image" src="https://user-images.githubusercontent.com/38483996/64926262-2a4f2280-d7c1-11e9-8d2a-fa01c45da63a.png">

**Comment by apexad** [comment]
Does it do this if you turn off polling?

**Comment by apexad** [comment]
So I believe this is occurring because there are actually 2 get commands that are bound:

‘’’JavaScript

  if (this.stateCommand) {
    this.garageDoorService.getCharacteristic(Characteristic.CurrentDoorState)
    .on('get', this.getState.bind(this));
    this.garageDoorService.getCharacteristic(Characteristic.TargetDoorState)
    .on('get', this.getState.bind(this));
  }
‘’’
The Home App is running them both. They are both necessary. However for the original poster one is clearly reporting the wrong state. I will have to take a look at this to figure out why.

**Comment by apexad** [comment]
Likely related to the issue described in https://github.com/apexad/homebridge-garagedoor-command/issues/12

**Comment by apexad** [comment]
@tastycorn Any reason why you are not using https://github.com/benlamonica/homebridge-rasppi-gpio-garagedoor versus my plugin?  Seems like this may work based on what you mentioned is your setup. This plugin seems to manage 'targetDoorState' when not changing the door state better.  I will have a test branch up in a few days with a possible fix based on some of the things done in that plugin.

**Comment by tastycorn** [comment]
> @tastycorn Any reason why you are not using https://github.com/benlamonica/homebridge-rasppi-gpio-garagedoor versus my plugin? Seems like this may work based on what you mentioned is your setup. This plugin seems to manage 'targetDoorState' when not changing the door state better. I will have a test branch up in a few days with a possible fix based on some of the things done in that plugin.

I have installed the plugin you recommended and spent all day getting it to work properly. In the end, it does in fact work and does not give me the same problems. I think the issue with your plugin is that it calls the script to check the state twice at the same time, and since my script was setting one GPIO as an output, another as an input, then reading from the input, then cleaning up all the GPIO pins, I was probably running into issues with both instances of the script trying to modify pins at the same time. I suppose I could have got around this by running a single script once to set up the pins, then just reading the status of the input pin in /sys/ with the script. Your plugin would still do it twice, but at least the output would be the same in both instances.

**Comment by apexad** [comment]
I am glad that other plugin worked for you.

 I think your analysis is correct, but as I mentioned in my testing the dual polling is due to ‘target door state’ and ‘current door state’ being polled. This is a HomeKit issue at the core. The GPIO pin garage door plugin just handles it better, but it has to still be doing this from what I can tell.

**Comment by HunterDG** [comment]
care to elaborate on the core HomeKit issue?  Double polling doesn't make sense on its face and I imagine native HomeKit implementations don't suffer from this.

**Comment by apexad** [comment]
So, in relation to a garage door, there are 2 states, CURRENT and TARGET. When you make a request to ‘OPEN’ for example this sets TARGET to OPEN, but CURRENT is CLOSED and possibly OPENING before it eventually becomes OPEN.

**Comment by HunterDG** [comment]
Thanks very much!
