### ISSUE TITLE
Advice on determining opening and closing states

### ISSUE THREAD

**Issue by johndierks** [apexad/homebridge-garagedoor-command#20]
Hi, thanks for the great plugin. I’m getting my feet wet with homebridge and hope to make my garage door my first device. 

I know this question is outside the scope of this plugin, but hope you’ll indulge my question.

Is there any good way to differentiate opening and closing states of my door?

Its easy enough to determine open and closed with one or two reed switches mounted at appropriate places, but I’m kind of hooked on figuring out of there is a good way to determine the door direction of a normal dumb garage door. 

I am especially interested as the direction can be changed with the installed door buttons outside of the knowledge of my homebridge. 

Any thoughts?

Cheers.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by apexad** [comment]
So, generally speaking, this is handled via the plugin itself with timers. Not something that is easily possible with a read switch or even a tilt sensor.

**Comment by johndierks** [comment]
Thanks. The two ideas I had were to measure the distance from the motor to the trolley using a proximity sensor of some sort, or measure the rotation of the spring loaded axel. Neither are off the shelf solutions but could be a fun project to tackle. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
