### ISSUE TITLE
./check_state.sh

### ISSUE THREAD

**Issue by dusankeprta** [apexad/homebridge-garagedoor-command#24]
Hello.

The command ./check_state.sh is not called in initial time when homebridge is restarted.
Unfortunately I see garage door are opened , however , couple minutes later , the check_state shell  is called and running properly.
And in the logg there is no any record regarding ./check_state , only after few minutes.

[6/22/2020, 2:48:38 PM] Homebridge is running on port 51826.
[6/22/2020, 2:51:54 PM] [Garage Door2] State of Garage Door2 is: CLOSED
[6/22/2020, 2:51:54 PM] [Garage Door2] State of Garage Door2 is: CLOSED

Thank you
Dusan

**Comment by apexad** [comment]
This may require a re-write of the plugin so it has better startup to run check state.  I don't have an eta of when I will be able to do this.  If you can, please submit a PR.

**Comment by dusankeprta** [comment]
Seems , If  the delay values are writing  as numbers the issue is disappeared.
           ...
            "status_update_delay": 15,
            "poll_state_delay": 20,
            ...
Thank you.
