### ISSUE TITLE
Trying to open a garage door that is already open.

### ISSUE THREAD

**Issue by dklein2017** [apexad/homebridge-garagedoor-command#25]
I was hoping there was a way to pass though to homekit that the garage is already open when trying to open it or the vice versa. Right now without writing the appropriate logic into the shell or python files to prevent this from happening, the garage will close when asked to be opened when it is already open. Here is the desired actions that I want to see from siri:

(Garage door is closed)
"Hey siri, close the garage"
"The garage cannot be closed as it is already closed"

Here is what happens right now with the appropriate logic programmed into the shell file:

(Garage door is closed)
"Hey siri, close the garage"
"Garage door is closing"
(Nothing happens because I have the shell file check the garage state to make sure it is open before triggering the relay)

**Comment by apexad** [comment]
I'm not sure that I follow?  What's the issue with writing the logic into the python script?  Are you saying I should move this logic into the homebridge plugin?

There would be no way at all to get Siri to respond with "door is already closed" but certainly could make Siri do nothing.  Is that what you are thinking?
