### ISSUE TITLE
Characteristic Warnings

### ISSUE THREAD

**Issue by marcowiese** [apexad/homebridge-garagedoor-command#26]
Hi,

the plugins throws warning logs as follows:

`ESC[37m[3/24/2021, 10:41:05 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 10:41:05 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Target Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:12:00 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:12:00 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Target Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:12:04 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:12:04 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Target Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:36:52 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Target Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:36:52 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:37:04 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:37:04 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Target Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
ESC[37m[3/24/2021, 11:37:38 AM] ESC[39mESC[36m[homebridge-garagedoor-command]ESC[39m This plugin generated a warning from the characteristic 'Current Door State': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
`
Make sure the callback() is called.
Make sure you are catching any possible exceptions and still calling the callback() even if an error occurred.
If the action does take some time to complete, adjust your plugin code to return the callback() instantly, and call characteristic.updateValue once the action has completed.

**Comment by apexad** [comment]
I'm on a small break from homebridge plugin, but will look at the as soon as I can. Will gladly merge PRs too.
