### ISSUE TITLE
Add characteristics

### ISSUE THREAD

**Issue by AdamVR7** [apexad/homebridge-garagedoor-command#27]
Hi!
Please add the following characteristics “manufacturer”, “model” and “serial”.

**Comment by apexad** [comment]
Duplicate of #26

**Comment by apexad** [comment]
So, what do you mean?  Do you want to be able to edit them?  They should be there...

```javascript
  this.informationService = new Service.AccessoryInformation();
  this.garageDoorService = new Service.GarageDoorOpener(this.name);

  this.informationService
  .setCharacteristic(Characteristic.Manufacturer, 'Garage Command')
  .setCharacteristic(Characteristic.Model, 'Homebridge Plugin')
  .setCharacteristic(Characteristic.SerialNumber, '001');
``

**Comment by AdamVR7** [comment]
.
.
.
this.manufacturer = config.manufacturer || 'Garage Command';
this.model = config.model || 'Homebridge Plugin';
this.serial = config.serial || '001';
.
.
.
this.informationService
  .setCharacteristic(Characteristic.Manufacturer, this.manufacturer)
  .setCharacteristic(Characteristic.Model, this.model)
  .setCharacteristic(Characteristic.SerialNumber, this.serial);

**Comment by apexad** [comment]
I will add these config options later today

**Comment by apexad** [comment]
added in 0.5.2
