### ISSUE TITLE
Lots of defunct sh zombie processes

### ISSUE THREAD

**Issue by AdamVR7** [apexad/homebridge-garagedoor-command#29]
Hi!
After updating the plugin to version 6.0, a lot of processes [sh] <defunct> appeared. What's the problem?
![CB08A497-17DD-4CB8-A7F0-77AA77A127BA](https://user-images.githubusercontent.com/62243592/113558830-081e2f00-9609-11eb-9705-34d22ecec401.jpeg)

**Comment by apexad** [comment]
My apologies as I don't actually use this plugin myself anymore, just trying to maintain it.  I believe this may be be caused by the exec command not having options set, including timeout.  v0.7.0 should fix this.
