### ISSUE TITLE
./check_state.sh

### ISSUE THREAD

**Issue by kodibrain** [apexad/homebridge-garagedoor-command#3]
Hi,
hi, what must be in the ./check_state.sh?

**Comment by apexad** [comment]
At minimum:
`echo 'CLOSED'`

However, I wrote this home bridge plugin to work with node js utility to control a Lowe's Iris Garage Door. Using that, it would actually be something like: `node /home/pi/garage/state.js` and it would look something like this [examlple](https://github.com/apexad/node-iris-aladdin-connect-garage-door/blob/master/example/state.js).

Hope that helps.

**Comment by kodibrain** [comment]
Thank you
I want to open my garage with a 433MHz code. But I have no idea how to do that.

**Comment by apexad** [comment]
If you have an extra remote I think most people just wire them so the battery for the remote is actually a raspberry pi. Tare a look at some homebridge garage gpio plugin.
