### ISSUE TITLE
Accessory not starting after latest update

### ISSUE THREAD

**Issue by UnderEu** [apexad/homebridge-garagedoor-command#30]
I just updated the plugin to latest release (v0.7.0) and it stopped working after restarting the service. The same issue occurs downgrading to any version post 0.4.1.
Had to downgrade to v0.4.1 in order to restore my setup.

See attached log.

[homebridge-sample.log](https://github.com/apexad/homebridge-garagedoor-command/files/6268200/homebridge-sample.log)

**Comment by UnderEu** [comment]
Homebridge version: 1.3.4 (Service Mode)
Node version: 14.16.1 (LTS branch)
NPM version: 7.8.0

Machine: Raspberry Pi 4 Model B (8GB)
OS: Ubuntu 20.04.2 LTS (aarch64)

**Comment by apexad** [comment]
Thanks for the logs... please confirm this is fixed in 0.7.1

**Comment by UnderEu** [comment]
It didn't work and, to make matters worse, it spammed my open/close script REALLY HARD - that almost crashed my garage opener.

New log sample attached

[homebridge-sample 0.7.1.log](https://github.com/apexad/homebridge-garagedoor-command/files/6268551/homebridge-sample.0.7.1.log)

**Comment by apexad** [comment]
ugh, try homebridge-garagedoor-command@0.8.0-beta.0 please

**Comment by apexad** [comment]
I've actually gone ahead with 0.8.0 as I don't want others using this reporting issues.  This is basically 0.4.1 with a different fix for undefined current door state and model/manufacture/serial fix.

**Comment by UnderEu** [comment]
0.8.0 is working. The "undefined current door state and model/manufacture/serial" stuff doesn't matter to me, the core function is the important thing.

I've encountered new bugs in this release, will open new issues to them.
