### ISSUE TITLE
[0.8.0] Config-UI Plugin Settings isn't working

### ISSUE THREAD

**Issue by UnderEu** [apexad/homebridge-garagedoor-command#33]
After update to 0.8.0, the Settings page on Config-UI > Plugins isn't working anymore, showing the following notification as a result:
![Screenshot 2021-04-07 at 07 42 01](https://user-images.githubusercontent.com/16519758/113946908-d6ab8c00-97df-11eb-80d7-72c9c48ae035.png)

Homebridge version: 1.3.4
Node version: 14.16.1 (LTS branch)
NPM version: 7.8.0

**Comment by apexad** [comment]
This should be fixed in 0.8.1
Looking at your other issue now

**Comment by QBJack** [comment]
I would like to reopen this issue as config-ui settings do not work 100%. I tried to set "Branding Settings" but they are not written to config file - my inputs just disappears.

Homebridge version: 1.3.4
Node version: 14.16.1
NPM version: 7.8.0

**Comment by apexad** [comment]
should work in 0.8.3 now

**Comment by QBJack** [comment]
Thanks for the fast fix, it works like expected!
