### ISSUE TITLE
The plugin slows down hombridge

### ISSUE THREAD

**Issue by tockancs** [apexad/homebridge-garagedoor-command#34]
Every few minutes this warning appears in homebridge log:
`[homebridge-garagedoor-command] This plugin slows down Homebridge. The read handler for the characteristic 'Current Door State' was slow to respond! See https://git.io/JtMGR for more info.`
I'm using homebridge v1.3.4, plugin v0.8.4, Node.js v14.15.1, Npm v6.14.9

**Comment by apexad** [comment]
This is somewhat related to other issues, such as https://github.com/apexad/homebridge-garagedoor-command/issues/35, which talks about how his plugin is not handling interim states like CLOSING well.  When I correct this and close that issue (no ETA), it will more than likely implement an async process that would get rid of this error.
