### ISSUE TITLE
state API's return value does not get parsed

### ISSUE THREAD

**Issue by shekarpathi** [apexad/homebridge-garagedoor-command#36]
I have a C executable called getGarageDoorState, which looks like the following

```
// getGarageDoorState.c

int main (void)
{
  wiringPiSetup () ;
  pinMode (25, OUTPUT) ;
  pinMode (26, INPUT) ;
  pinMode (27, INPUT) ;

  if (digitalRead(26) && digitalRead(27)) {  // return CLOSING
    printf("OPENING\n");
  }

  if (!digitalRead(26) && !digitalRead(27)) { // return OPENING
    printf("CLOSING\n");
  }

  if (!digitalRead(26) && digitalRead(27)) { // return OPEN
    printf("OPEN\n");
  }

  if (digitalRead(26) && !digitalRead(27)) { // return CLOSED
    printf("CLOSED\n");
  }

  return 0 ;
}
```
When the door is open, the states on the Homekit app on my iPhone says "Open" and is white in color. This is GOOD.

But, when the door is closed, the status of the icon on the Homekit app on my iPhone says "Opening..". This is NOT correct. I think, the return value "CLOSED", is not parsed by the index.js file, hence it is showing wrong status.

Do you know why?

Besides this, this is a super program and I like it. Hope I can get this minor issue resolved. I am not very good in node.js

**Comment by apexad** [comment]
I'm curious about the `\n` in the code but otherwise, this seems similar to https://github.com/apexad/homebridge-garagedoor-command/issues/35
