### ISSUE TITLE
Polling

### ISSUE THREAD

**Issue by Tommrodrigues** [apexad/homebridge-garagedoor-command#6]
Hi there,

I really appreciate the work you've put into this plugin and it is exactly what I've been looking for! I've had a lot of fun working with this plugin but there is one small thing that I wish was available which is polling. This is due to the fact that after changing the state of the accessory in the home app, you have to leave then re-enter the app for it to achieve the CLOSED/OPEN state. Whilst this is more of an aesthetic concern rather than a practical one as the accessory still carries out the command, I would be very appreciative if you could implement polling to eliminate this problem. 

Thank you in advance for your help,
Kind Regards,
Tom

**Comment by apexad** [comment]
Duplicate https://github.com/apexad/homebridge-garagedoor-command/issues/2
